[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"

# CI backends to support
ci = "github"

# Add github attestations
github-attestations = true
# Whether to install an updater program
install-updater = true
# Path that installers should place binaries in
install-path = ["$XDG_BIN_HOME/", "$XDG_DATA_HOME/../bin", "~/.local/bin"]
# The installers to generate for each app
installers = ["shell", "npm", "homebrew"]
# The archive formats
windows-archive = ".zip"
unix-archive = ".tar.gz"

# Local artifacts jobs to run in CI
local-artifacts-jobs = ["./build-docker"]
# Publish jobs to run in CI
publish-jobs = ["./publish-homebrew", "./publish-npm", "./publish-wasm"]

# A namespace to use when publishing this package to the npm registry
npm-scope = "@franco-grobler"
# Homebrew tap 
tap = "franco-grobler/tap"

# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]

[dist.github-action-commits]
"actions/checkout" = "8e8c483db84b4bee98b60c0593521ed34d9990e8"                # v6.0.1
"actions/upload-artifact" = "b7c566a772e6b6bfb58ed0dc250532a479d7789f"         # v6.0.0
"actions/download-artifact" = "37930b1c2abaa49bbe596cd826c3c89aef350131"       # v7.0.0
"actions/attest-build-provenance" = "c074443f1aee8d4aeeae555aebba3282517141b2" # v2.2.3
