[package]
name = "cowsay"
version = "0.0.1"
publish = true
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "../../README.md"
default-run = "cowsay"

[lib]
name = "cowsay_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
clap = { workspace = true }
